### ISSUE TITLE
Cannot save checkpoints 

### ISSUE THREAD

**Issue by javierunix** [jonbruner/ezgan#1]
When I run EZGAN.ipynb, I have the following error: Parent directory of models/pretrained_gan.ckpt doesn’t exist, can’t save.

**Comment by jonbruner** [comment]
Thanks for pointing this out. The script saves checkpoints periodically into a directory called `models` that should be located in the working directory. I'll add that to the repo so that it should be possible to clone and run.

In the meantime, it should be possible to run this by adding a directory called `models` to the directory that contains the script.

**Comment by jonbruner** [comment]
Added `models` directory, including a sample checkpoint, so that it should be possible to clone and run.
